server:
  port: 8088  #服务端口
spring:
  application:
    name: test-freemarker #指定服务名
  freemarker:
     cache: false    #关闭模板缓存,方便测试
     settings:
         template_update_delay: 0 #检查模板更新延迟时间,设置为0,方便进行模板测试

